### ISSUE TITLE
How, in theory, to support arbitrary parsers?

### ISSUE THREAD

**Issue by t3db0t** [brendonboshell/supercrawler#11]
I'm considering extending supercrawler to support Phantom or https://github.com/GoogleChrome/puppeteer (i.e. Headless Chrome, as a modern alternative to PhantomJS) for the purposes of parsing dynamic content—do you have some ideas on how best to architect or re-architect this?

**Comment by t3db0t** [comment]
Presumably this would take the form of (ok, obviously) a custom parser handler that invokes the chosen library. OK, this looks more and more obvious now that I think about it. I'll give it a try tomorrow. Let me know if you have any advice!

**Comment by brendonboshell** [comment]
Yes, I recommend you create a custom content handler that will invoke headless Chrome. 

Alternatively, if you want to do complex parsing (and not in Javascript), you can run a proxy server elsewhere and crawl URLs of the format, e.g.:

```
http://localhost:4000/?url=[url here]
```

That server could return a simple HTML document with the list of parsed backlinks to be consumed by the `htmlLinkParser` handler (transform the URLs to the form `http://localhost:4000/?url=`) and it could contain some structured data (to be further processed from Node, for instance.)

The first solution is probably best, although the second strategy makes sense when you have pre-existing scraping/parsing logic in another language.
