### ISSUE TITLE
URLs statusCode NULL while there was no errors crawling

### ISSUE THREAD

**Issue by Abukamel** [brendonboshell/supercrawler#19]
Hello, thanks for the app, I was using it to crawl links of my website but  I found that it add `statusCode` `NULL` to crawled links in the database while there is no errors at all.

Why does it act like that, I consider a request is successful and should log it's success `statusCode` if there were no errors, also strangely not all of succeeded requests gives `statusCode` of `NULL`.

I have checked the access log also during the crawler work and found `200` responses to URLs that logs `statusCode` of `NULL`

![screenshot](https://user-images.githubusercontent.com/1246960/45878742-e04c8000-bdaa-11e8-8ec3-dd30d688032e.png)

**Comment by brendonboshell** [comment]
Since the next retry date is in the past, it would suggest these URLs have not yet been crawled (only scheduled). Please reopen if this is not the case.
