### ISSUE TITLE
set Referer

### ISSUE THREAD

**Issue by atomixstar** [brendonboshell/supercrawler#25]
Hi great tool, is there any way to set an referrer like the url of the page that lead the crawler to the current page.

URL                                         Destination
https://example.com              https://example.com/page1

Also is there possible to make the crawler scan all links but store in the database only the external links ?

Thank you very much

**Comment by brendonboshell** [comment]
It is not currently possible to set a referrer. I am not sure how this would work - what would happen if you saw a URL on two or more referring pages? Should it be crawled multiple times?

The crawler uses a database or Redis to store the URLs that are pending a crawl.

If you only want to crawl URLs that match a certain pattern, this is possible with a little work. Have a look at [htmlLinkParser](https://github.com/brendonboshell/supercrawler/blob/master/lib/handlers/htmlLinkParser.js) and [sitemapsParser](https://github.com/brendonboshell/supercrawler/blob/master/lib/handlers/sitemapsParser.js). You would need to implement your own HTML link parser that implemented some kind of filter.
