### ISSUE TITLE
How to configure to only crawl internal links of the url supplied?

### ISSUE THREAD

**Issue by nifflerco** [brendonboshell/supercrawler#28]
Basically we need to get all internal links of our user's websites so we only want to crawls internal links within supplied url.

Is it possible to configure supercrawler like that?

**Comment by brendonboshell** [comment]
The content handlers return an array of links that get added to the crawl queue. [htmlLinkParser](https://github.com/brendonboshell/supercrawler/blob/master/lib/handlers/htmlLinkParser.js#L34) supports a `hostnames` argument that can restrict crawling to a specific host. If you need more complex logic, you can implement your own content handler to extract the links.
