### ISSUE TITLE
controlling how deep to crawl

### ISSUE THREAD

**Issue by robschaefer** [brendonboshell/supercrawler#29]
I might have missed it, but in the crawler options i didnt see a way to control how deep the crawler goes.  Is that possible via a parameter, or would i have to implement that logic in the htmllinkParser handler via urlFilter?

**Comment by brendonboshell** [comment]
I think this would have to be implemented in a your own content handler, because it would at least require you to store the links and calculate the depth on this. I think it's too complex to be part of the `supercrawler` itself.
