### ISSUE TITLE
Ability to customize http request

### ISSUE THREAD

**Issue by sluramod** [brendonboshell/supercrawler#3]
pass custom headers, use cookie jar, etc.

**Comment by brendonboshell** [comment]
Should be a simple addition, I will take a look.

**Comment by brendonboshell** [comment]
Ability to provide custom options to request has been added in 1.1.0 (https://github.com/brendonboshell/supercrawler/commit/58dda5bbd57d23cc77d78a7e1e1d91650d64c904)

Documentation has been added to the README: https://github.com/brendonboshell/supercrawler#crawler

Example:

```js
var crawler = new supercrawler.Crawler({
  interval: 100,
  concurrentRequestsLimit: 5,
  urlList: new supercrawler.RedisUrlList({
    redis: {
      port: 6379,
      host: '127.0.0.1'
    }
  }),
  request: {
    headers: {
      'x-custom-header': 'example'
    }
  }
});
```
