### ISSUE TITLE
How to periodically crawl again

### ISSUE THREAD

**Issue by Hyra** [brendonboshell/supercrawler#40]
I see in the database there is a field for `nextRetryDate` which i assume is used for failed requests.

How would one make it so that a domain/url can be "re-crawled" let's say every day?

At the moment, once a url is finished, it won't touch it again.

**Comment by scottburton11** [comment]
We're using a cron job to trigger a script that looks like this:
`
const supercrawler = require("supercrawler");

var crawler = new supercrawler.Crawler({
  urlList: new supercrawler.RedisUrlList({
    redis: process.env.REDIS_URL
  }),
});

crawler.getUrlList().insertIfNotExists(new supercrawler.Url("SOME URL"))

// https://github.com/brendonboshell/supercrawler/issues/7
process.exit();
`

"SOME URL" could come from a database, for example.

A second process runs a persistent crawler and is always running.

**Comment by hjr3** [comment]
The [next crawl date logic](https://github.com/brendonboshell/supercrawler/blob/6f851078faf0b7972fd5bdbbf75e58361d55fd47/lib/DbUrlList.js#L182) is hard coded. I think it should should use the [recrawlInMs](https://github.com/brendonboshell/supercrawler/blob/6f851078faf0b7972fd5bdbbf75e58361d55fd47/lib/DbUrlList.js#L36) option.

I will throw a PR up in a few days unless you get to it first.

**Comment by brendonboshell** [comment]
`DbUrlList` takes a `recrawlInMs` option. This option is used when a URL is crawled successfully to schedule the next crawl. Please re-open if this does not work.

**Comment by Hyra** [comment]
Very awesome :)
