### ISSUE TITLE
Is there a way to get the ID of the inserted link on the addHandler("text/html", function(context)). My first time in git posting a issue, maybe this is not a issue :)

### ISSUE THREAD

**Issue by AvdiuAndin** [brendonboshell/supercrawler#8]

**Comment by brendonboshell** [comment]
I assume you mean get an attribute from the `<a>` element? Take a look at [htmlLinkParser.js](https://github.com/brendonboshell/supercrawler/blob/master/lib/handlers/htmlLinkParser.js) as an example - [this is where it gets the `href` attribute](https://github.com/brendonboshell/supercrawler/blob/master/lib/handlers/htmlLinkParser.js#L24), for instance:

```js
targetHref = $this.attr("href");
```

Let me know if that helps.

**Comment by AvdiuAndin** [comment]
The id of the inserted link in the database. Sorry for not explaining it correctly

**Comment by brendonboshell** [comment]
Ah, okay. Unfortunately, there is no way because having an `id` is not a requirement of `UrlList` - e.g. there is no numeric ID when using Redis or FifoUrlList. This is simply an implementation detail of `DbUrlList` and is therefore not exposed.

**Comment by AvdiuAndin** [comment]
Can u suggest what can I modify in order to get the id of the inserted link on the addhandler("text/html",function(context){}) method

**Comment by AvdiuAndin** [comment]
Ok i have a way to get the id, but is nooo good at all. I get the url from the context.url and I do a an extra request for the id. what if there are a 100k links inserted. A STRING search, way too bad :(.

**Comment by brendonboshell** [comment]
The links are inserted in batch once the handlers are finished running, hence you cannot obtain the ID from within the handlers. I am not sure what you are trying to achieve, but you could try creating your own `UrlList` that inherits `EventEmitter` and emit an event for each inserted URL. I recommend against using the database table for anything other than supercrawler - ideally, you should create your own list of URLs if you need them elsewhere.

**Comment by michael-tourneur** [comment]
Actually I have the same request.
Would be good to have the id to match on one of our custom table to the table url used by the crawler.
